/**------------------------------COMPLEXITY-REDUCTION---------------------------*/

	-- WHAT WILL HAPPEN WHEN ALL THE USERS HAVE THE READ PERMISSION TO THE DB
		
		-- REDUNDENCY
		-- PERFROMANCE ISSUES
		-- COMPLEXITY
		-- HARD TO MAINTAIN
		-- DB STRESS
		-- SECURITY

	-- SOLUTION FOR THIS
		
		-- SUBQUERY
		-- CTE
		-- VIEWS
		-- TEMP TABLES
		-- CTAS

	-- DB ARCHITECTURE
		
		-- SERVER - CLIENT 

		-- DB ENGINE - HANDLE ALL THE OPERATIONS
		-- STORAGE 
			-- DISK -- PERMANENT CAN STORE LARGE DATA IT IS SLOW
				-- USER -- MAIN CONTENT OF THE DATA -- USERS DATA
				-- CATELOG -- FOR ITS OWN INFO --> DB TRACK ABOUT DB ITSELF META DATA
					-- INFORMATION SCHEMA HELPS TO EXPLOR ABOUT THE TABLES IN THE DB
						
						/**-------------------------------------------*/
							
							SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

							SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS

						/**------------------*/
				
				-- TEMP STORAGE 
						-- TEMP SPACE USED BY DB FOR SHORT-TERM TASK
						-- PROCESSING QUERY AND SORTING DATA
				
			-- CACHE -- SHORT TIME MEMORY TO STORE DATA IT IS FAST 
		
			










